source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'UIViewHelper_Example', :exclusive => true do
  pod "UIViewHelper", :path => "../"
end

target 'UIViewHelper_Tests', :exclusive => true do
  pod "UIViewHelper", :path => "../"

  
end
